steps:
  - name: vizzu/vizzu-dev-wasm:0.8
    id: init
    waitFor:
      - '-'
    entrypoint: bash
    args:
      - '-c'
      - |-
        npm run init
    dir: /workspace

  - name: vizzu/vizzu-dev-wasm:0.8
    id: ci-src
    waitFor:
      - init
    entrypoint: bash
    args:
      - '-c'
      - |-
        npm run format-src &&
        npm run lint-src
    dir: /workspace
  - name: vizzu/vizzu-dev-wasm:0.8
    id: ci-docs
    waitFor:
      - init
    entrypoint: bash
    args:
      - '-c'
      - |-
        npm run format-docs &&
        npm run lint-docs
    dir: /workspace
  - name: vizzu/vizzu-dev-wasm:0.8
    id: ci-tools
    waitFor:
      - init
    entrypoint: bash
    args:
      - '-c'
      - |-
        npm run format-tools &&
        npm run lint-tools &&
        npm run type-tools
    dir: /workspace

  - name: vizzu/vizzu-dev-desktop:0.8
    id: build-desktop-clangformat
    waitFor:
      - ci-src
      - ci-docs
      - ci-tools
    entrypoint: bash
    args:
      - '-c'
      - |-
        ./tools/ci/run/pkg-build-desktop-clangformat.sh
    dir: /workspace

  - name: vizzu/vizzu-dev-desktop:0.8
    id: build-desktop-clangtidy
    waitFor:
      - build-desktop-clangformat
    entrypoint: bash
    args:
      - '-c'
      - |-
        ./tools/ci/run/pkg-build-desktop-clangtidy.sh
    dir: /workspace
  - name: vizzu/vizzu-dev-wasm:0.8
    id: build-wasm
    waitFor:
      - build-desktop-clangformat
    entrypoint: bash
    args:
      - '-c'
      - '-i'
      - |-
        source /root/.bashrc &&
        ./tools/ci/run/pkg-build-wasm.sh
    dir: /workspace

  - name: vizzu/vizzu-dev-wasm:0.8
    id: build-js
    waitFor:
      - build-wasm
    entrypoint: bash
    args:
      - '-c'
      - |-
        ./tools/ci/run/pkg-init-js.sh &&
        mv build/js/* build/js/vizzu.tgz
    dir: /workspace

  - name: gcr.io/cloud-builders/gsutil
    id: upload-sha
    waitFor:
      - build-js
    entrypoint: bash
    args:
      - '-c'
      - |-
        gsutil -m cp -r 'dist/*' 'gs://vizzu-lib-main-sha/lib-$SHORT_SHA' &&
        gsutil -m cp -r 'build/js/*' 'gs://vizzu-lib-main-sha/lib-$SHORT_SHA'
    dir: /workspace

  - name: vizzu/vizzu-dev-wasm:0.8
    id: test
    waitFor:
      - build-js
    entrypoint: bash
    args:
      - '-c'
      - |-
        npm run test-unit-test &&
        npm test -- --vizzu /dist/vizzu.min.js --vizzu-ref /dist/vizzu.min.js --images DISABLED --hashes DISABLED --nologs
    dir: /workspace

  - name: gcr.io/cloud-builders/git
    id: docs-init
    waitFor:
      - test
    entrypoint: bash
    args:
      - '-c'
      - |
        echo "$$VIZZUHQ_GITHUB_SSH" > /root/.ssh/id_rsa
        chmod 400 /root/.ssh/id_rsa
        ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts
    dir: /workspace
    secretEnv:
      - VIZZUHQ_GITHUB_SSH
    volumes:
      - name: ssh
        path: /root/.ssh

  - name: vizzu/vizzu-dev-wasm:0.8
    id: docs-build
    waitFor:
      - docs-init
    entrypoint: bash
    args:
      - '-c'
      - |-
        ./tools/ci/run/docs-thumbnails.sh &&
        ./tools/ci/run/docs-build.sh
    dir: /workspace

  - name: gcr.io/cloud-builders/git
    id: docs-publish
    waitFor:
      - docs-build
    entrypoint: bash
    args:
      - '-c'
      - |
        git checkout -b tmp
        git rm -r .
        git clean -df
        cp -r ../site/* .
        git add .
        git commit -m "Site development version"
        git push origin tmp:gh-pages-dev -f
    dir: /workspace/vizzu-lib-doc
    secretEnv:
      - VIZZUHQ_GITHUB_SSH
    volumes:
      - name: ssh
        path: /root/.ssh

  - name: gcr.io/cloud-builders/gsutil
    id: upload
    waitFor:
      - test
    entrypoint: bash
    args:
      - '-c'
      - |-
        if [ $BRANCH_NAME == "main" ]
        then
          for file in $(gsutil ls gs://vizzu-lib-main/lib/*); do
            filename=$(basename "$file")
            if [ "$filename" != "size.txt" ] && [ "$filename" != "sha.txt" ]; then
              gsutil rm "$file"
            fi
          done
          gsutil -m cp -r 'dist/*' 'gs://vizzu-lib-main/lib' &&
          echo $SHORT_SHA | gsutil cp - gs://vizzu-lib-main/lib/sha.txt &&
          gsutil cp 'build/cmake-wasm/weblib/size.txt' 'gs://vizzu-lib-main/lib' &&
          gsutil -m cp 'build/js/*' 'gs://vizzu-lib-main/lib' &&
          gsutil -m setmeta -r -h 'cache-control: max-age=0,public' 'gs://vizzu-lib-main/*'
        fi
    dir: /workspace

availableSecrets:
  secretManager:
    - versionName: projects/418279184538/secrets/VIZZUHQ_GITHUB_SSH/versions/latest
      env: VIZZUHQ_GITHUB_SSH
timeout: 2400s
options:
  machineType: E2_HIGHCPU_8
