steps:
  - name: vizzu/vizzu-dev-wasm:0.8
    id: init
    waitFor:
      - '-'
    entrypoint: bash
    args:
      - '-c'
      - |-
        npm run init
    dir: /workspace

  - name: gcr.io/cloud-builders/gsutil
    id: download-sha
    waitFor:
      - init
    entrypoint: bash
    args:
      - '-c'
      - |-
        mkdir dist &&
        gsutil -m cp -r 'gs://vizzu-lib-main/lib/*' 'dist'
    dir: /workspace

  - name: gcr.io/cloud-builders/git
    id: docs-init
    waitFor:
      - download-sha
    entrypoint: bash
    args:
      - '-c'
      - |
        echo "$$VIZZUHQ_GITHUB_SSH" > /root/.ssh/id_rsa &&
        chmod 400 /root/.ssh/id_rsa &&
        ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts &&
        git clone --single-branch --branch main --depth 1 'git@github.com:vizzuhq/vizzu-lib-doc'
    dir: /workspace
    secretEnv:
      - VIZZUHQ_GITHUB_SSH
    volumes:
      - name: ssh
        path: /root/.ssh

  - name: vizzu/vizzu-dev-wasm:0.8
    id: docs-build
    waitFor:
      - docs-init
    entrypoint: bash
    args:
      - '-c'
      - |-
        git config --global user.name "David Vegh" &&
        git config --global user.email "veghdev@gmail.com" &&
        git fetch git@github.com:vizzuhq/vizzu-lib-doc gh-pages:gh-pages --depth=1 &&
        git remote add vizzu-lib-doc git@github.com:vizzuhq/vizzu-lib-doc &&
        npm run docs-gen-thumbnail-gsutil &&
        npm run docs-deploy &&
        git push vizzu-lib-doc gh-pages:gh-pages
    dir: /workspace
    secretEnv:
      - VIZZUHQ_GITHUB_SSH
    volumes:
      - name: ssh
        path: /root/.ssh

availableSecrets:
  secretManager:
    - versionName: projects/418279184538/secrets/VIZZUHQ_GITHUB_SSH/versions/latest
      env: VIZZUHQ_GITHUB_SSH
timeout: 2400s
options:
  machineType: E2_HIGHCPU_8
