steps:
  - name: vizzu/vizzu-dev-wasm:0.8
    id: init
    waitFor:
      - '-'
    entrypoint: bash
    args:
      - '-c'
      - |-
        chmod +x tools/ci/run/* &&
        npm run init
    dir: /workspace

  - name: vizzu/vizzu-dev-wasm:0.8
    id: ci-src
    waitFor:
      - init
    entrypoint: bash
    args:
      - '-c'
      - |-
        npm run format-src &&
        npm run lint-src
    dir: /workspace
  - name: vizzu/vizzu-dev-wasm:0.8
    id: ci-docs
    waitFor:
      - init
    entrypoint: bash
    args:
      - '-c'
      - |-
        npm run format-docs &&
        npm run lint-docs
    dir: /workspace
  - name: vizzu/vizzu-dev-wasm:0.8
    id: ci-tools
    waitFor:
      - init
    entrypoint: bash
    args:
      - '-c'
      - |-
        npm run format-tools &&
        npm run lint-tools &&
        npm run type-tools
    dir: /workspace

  - name: vizzu/vizzu-dev-desktop:0.8
    id: build-desktop-clangformat
    waitFor:
      - ci-src
      - ci-docs
      - ci-tools
    entrypoint: bash
    args:
      - '-c'
      - |-
        ./tools/ci/run/pkg-build-desktop-clangformat.sh
    dir: /workspace

  - name: vizzu/vizzu-dev-desktop:0.8
    id: build-desktop-clangtidy
    waitFor:
      - build-desktop-clangformat
    entrypoint: bash
    args:
      - '-c'
      - |-
        ./tools/ci/run/pkg-build-desktop-clangtidy.sh
    dir: /workspace
  - name: vizzu/vizzu-dev-wasm:0.8
    id: build-wasm
    waitFor:
      - build-desktop-clangformat
    entrypoint: bash
    args:
      - '-c'
      - '-i'
      - |-
        source /root/.bashrc &&
        ./tools/ci/run/pkg-build-wasm.sh
    dir: /workspace

  - name: vizzu/vizzu-dev-wasm:0.8
    id: build-js
    waitFor:
      - build-wasm
    entrypoint: bash
    args:
      - '-c'
      - |-
        ./tools/ci/run/pkg-init-js.sh
    dir: /workspace

  - name: gcr.io/cloud-builders/gsutil
    id: upload-sha
    waitFor:
      - build-js
    entrypoint: bash
    args:
      - '-c'
      - |-
        gsutil -m cp -r 'dist/*' 'gs://vizzu-lib-main-sha/lib-$SHORT_SHA' &&
        gsutil -m cp -r 'build/js/*' 'gs://vizzu-lib-main-sha/lib-$SHORT_SHA'
    dir: /workspace

  - name: vizzu/vizzu-dev-wasm:0.8
    id: test
    waitFor:
      - build-js
    entrypoint: bash
    args:
      - '-c'
      - |-
        npm test -- --vizzu /dist/vizzu.min.js --vizzu-ref /dist/vizzu.min.js --images DISABLED --hashes DISABLED --nologs
    dir: /workspace

  - name: gcr.io/cloud-builders/gsutil
    id: upload
    waitFor:
      - test
    entrypoint: bash
    args:
      - '-c'
      - |-
        if [ $BRANCH_NAME == "main" ]
        then
          gsutil rm 'gs://vizzu-lib-main/lib/*' &&
          gsutil -m cp -r '/dist/lib/*' 'gs://vizzu-lib-main/lib' &&
          echo $SHORT_SHA | gsutil cp - gs://vizzu-lib-main/lib/sha.txt &&
          gsutil cp '/workspace/build/cmake-wasm/weblib/size.txt' 'gs://vizzu-lib-main/lib' &&
          gsutil -m setmeta -r -h 'cache-control: max-age=0,public' 'gs://vizzu-lib-main/*'
        fi
    dir: /workspace

timeout: 1800s
options:
  machineType: E2_HIGHCPU_8
