name: CD

on:
  release:
    types: [published]

jobs:
  init:
    uses: ./.github/workflows/init.yml

  doc:
    uses: ./.github/workflows/doc.yml
    needs: init

  release:
    uses: ./.github/workflows/release.yml
    secrets: inherit
    needs: init
