name: CI

on:
  workflow_call:

jobs:
  check_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Cache dev-py environment
        uses: actions/cache@v3
        with:
          path: ./tools/docs/.venv_vizzu
          key: dev-py-${{ hashFiles('./tools/docs/dev-requirements.txt') }}

      - name: Init dev-py environment
        run: |
          make check-dev-py
          make dev-py
        working-directory: ./tools/docs

      - name: Cache dev-js environment
        uses: actions/cache@v3
        with:
          path: ./tools/docs/node_modules
          key: dev-js-${{ hashFiles('./tools/docs/package-lock.json') }}

      - name: Init dev-js environment
        run: |
          make check-dev-js
          make dev-js
        working-directory: ./tools/docs

      - name: Check format
        run: make check-format
        working-directory: ./tools/docs

      - name: Check lint
        run: make check-lint
        working-directory: ./tools/docs

      - name: Check typing
        run: make check-typing
        working-directory: ./tools/docs
