name: Documentation

on:
  workflow_dispatch:
  workflow_call:

jobs:
  publish_docs:
    runs-on: ubuntu-22.04

    steps:
      - name: Trigger Cloud Build
        run: |
          curl -X POST -H "Content-type: application/json" "https://cloudbuild.googleapis.com/v1/projects/vizzu-ci/triggers/vizzu-lib-docs:webhook?key=${{ secrets.VIZZUHQ_GCP_BUILD }}" -d "{}"
