name: Init

on:
  workflow_call:

jobs:
  init_dev_ubuntu22:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Cache dev-js environment
        id: cache_dev_js_ubuntu22
        uses: actions/cache@v3
        with:
          path: node_modules
          key: cache_dev_js_ubuntu22_${{ hashFiles('package-lock.json') }}

      - name: Init dev-js environment
        if: steps.cache_dev_js_ubuntu22.outputs.cache-hit != 'true'
        run: |
          npm run init-js

      - name: Init package
        run: |
          npm run pkg-rollup-jsonly ${GITHUB_SHA:0:7} &&
          npm run pkg-init-js

      - name: Cache package
        uses: actions/cache@v3
        with:
          path: |
            README.md
            package.json
            build/js/
            dist/
          key: cache_package_${{ github.run_id }}
